### ISSUE TITLE
[BUG]  Intermittent failing tests

### ISSUE THREAD

**Issue by Alphonce-Mutebi** [Kukuza/sargo-smart-contracts#10]
After setting up my local environment, I ran **npx hardhut test** the first time and the tests failed and upon running the tests the second time they both ran. See the logs below
<img width="1066" alt="Screenshot 2022-03-15 at 16 34 13" src="https://user-images.githubusercontent.com/37070861/158492325-73572426-8299-4269-b9c7-5a41ba95daae.png">
<img width="936" alt="Screenshot 2022-03-15 at 16 33 49" src="https://user-images.githubusercontent.com/37070861/158492333-d289c59c-5216-480a-a571-f17a110d9796.png">

**Comment by Allen-Muhani** [comment]
@Alphonce-Mutebi  Is this still an issue?
